version: '3'

services:
  news-api:
    build:
      context: .
      dockerfile: ./etc/kin-news/Dockerfile
    image: "kin-news-api"
    container_name: "kin-news-api"
    command: bash -c "alembic revision --autogenerate && alembic upgrade head && python -m kin_news_api start-app"
    env_file:
      - ./etc/kin-news/env/.dev.env
    ports:
      - "8000:8000"
    networks:
      - kin-network
    volumes:
      - ./kin_news_api:/app/kin_news_api
      - ./submodules/kin-news-core/kin_news_core:/app/kin_news_core
      - ./etc/kin-news/migrations:/app/migrations
      - ./etc/kin-news/alembic.ini:/app/alembic.ini
      - ./media/:/media

  nginx-images-serving:
    image: nginx:1.19.0
    ports:
      - "8002:80"
    volumes:
      - ./nginx-images-serving/nginx.conf:/etc/nginx/nginx.conf
      - ./media/:/media

networks:
  kin-network:
    external:
      name: kin-network
