version: '3'

services:
  statistics-api:
    build:
      context: .
      dockerfile: ./etc/kin-stats/Dockerfile
    image: 'kin-statistics-api'
    container_name: 'kin-statistics-api'
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    env_file:
      - ./etc/kin-stats/env/.dev.env
    ports:
      - "8001:8000"
    networks:
      - kin-network
    volumes:
      - ./kin_statistics_api/api:/app/api
      - ./kin_statistics_api/setup.cfg:/app/setup.cfg
      - ./kin_statistics_api/config:/app/config
      - ./kin_statistics_api/models:/app/models
      - ./kin_statistics_api/data:/app/data
      - ./submodules/kin-news-core/kin_news_core:/app/kin_news_core

  celery_worker:
    build:
      context: .
      dockerfile: ./etc/kin-stats/Dockerfile
    image: 'kin-statistics-worker'
    container_name: 'kin-statistics-celery-worker'
    command: bash -c "celery -A config worker -l INFO"
    env_file:
      - ./etc/kin-stats/env/.dev.env
    networks:
      - kin-network
    volumes:
      - ./kin_statistics_api/api:/app/api
      - ./kin_statistics_api/config:/app/config
      - ./kin_statistics_api/models:/app/models
      - ./kin_statistics_api/data:/app/data
      - ./submodules/kin-news-core/kin_news_core:/app/kin_news_core
    depends_on:
      - statistics-api

networks:
  kin-network:
    external:
      name: kin-network
