version: '3'

services:
  test-statistics-api:
    build:
      context: .
      dockerfile: ./etc/kin-stats/Dockerfile
    image: 'kin-statistics-api'
    container_name: 'kin-statistics-api-test'
    command: bash -c "python manage.py test"
    env_file:
      - ./etc/kin-stats/env/.test.env
    volumes:
      - ./kin_statistics_api/api:/app/api
      - ./kin_statistics_api/setup.cfg:/app/setup.cfg
      - ./kin_statistics_api/config:/app/config
      - ./kin_statistics_api/models:/app/models
      - ./kin_statistics_api/data:/app/data
      - ./submodules/kin-news-core/kin_news_core:/app/kin_news_core
    depends_on:
      - postgres
      - mongo

  postgres:
    image: "postgres"
    container_name: "postgres-stats-test"
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=kin-stats-test
      - POSTGRES_USER=kin-stats-user
      - POSTGRES_PASSWORD=kin-stats-password

  mongo:
    image: "mongo:6.0.3"
    container_name: "mongo-test"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=kin-news-user-test
      - MONGO_INITDB_ROOT_PASSWORD=kin-news-password-test
    ports:
      - "27017:27017"
