version: '3'

services:
  statistics-api:
    build:
      context: .
      dockerfile: ./etc/kin-stats/Dockerfile
    image: 'kin-statistics-api'
    container_name: 'kin-statistics-api'
    command: bash -c "alembic-autogen-check || alembic revision --autogenerate && alembic upgrade head && python -m kin_statistics_api run-server"
    env_file:
      - ./etc/kin-stats/env/.dev.env
    ports:
      - "8001:8000"
    networks:
      - kin-network
    volumes:
      - ./etc/kin-stats/migrations:/app/migrations
      - ./etc/kin-stats/alembic.ini:/app/alembic.ini
      - ./kin_statistics_api:/app/kin_statistics_api
      - ./submodules/kin-news-core/kin_news_core:/app/kin_news_core

  celery_worker:
    build:
      context: .
      dockerfile: ./etc/kin-stats/Dockerfile
    image: 'kin-statistics-worker'
    container_name: 'kin-statistics-celery-worker'
    command: bash -c "python -m kin_statistics_api run-tasks"
    env_file:
      - ./etc/kin-stats/env/.dev.env
    networks:
      - kin-network
    volumes:
      - ./etc/kin-stats/migrations:/app/migrations
      - ./etc/kin-stats/alembic.ini:/app/alembic.ini
      - ./kin_statistics_api:/app/kin_statistics_api
      - ./submodules/kin-news-core/kin_news_core:/app/kin_news_core
    depends_on:
      - statistics-api

networks:
  kin-network:
    external:
      name: kin-network
