version: '3'

services:
  statistics-api:
    build:
      context: .
      dockerfile: ./etc/service/Dockerfile
    image: 'kin-statistics-api'
    container_name: 'kin-statistics-api'
    command: bash -c "alembic upgrade head && python -m kin_statistics_api run-server"
    env_file:
      - ./etc/service/env/.dev.env
    ports:
      - "8001:8000"
    networks:
      - kin-network
    volumes:
      - ./etc/service/migrations:/app/migrations
      - ./etc/service/alembic.ini:/app/alembic.ini
      - ./src/kin_statistics_api:/app/kin_statistics_api
      - ./src/setup.cfg:/app/setup.cfg
      - ./submodules:/submodules
      - ./src/poetry.lock:/app/poetry.lock
      - ./src/pyproject.toml:/app/pyproject.toml

  statistics-consumer:
    build:
      context: .
      dockerfile: ./etc/service/Dockerfile
    image: 'kin-statistics-consumer'
    container_name: 'kin-statistics-consumer'
    command: bash -c "python -m kin_statistics_api run-rabbitmq"
    env_file:
      - ./etc/service/env/.dev.env
    networks:
      - kin-network
    volumes:
      - ./etc/service/migrations:/app/migrations
      - ./etc/service/alembic.ini:/app/alembic.ini
      - ./src/kin_statistics_api:/app/kin_statistics_api
      - ./src/setup.cfg:/app/setup.cfg
      - ./submodules:/submodules
      - ./src/poetry.lock:/app/poetry.lock
      - ./src/pyproject.toml:/app/pyproject.toml

networks:
  kin-network:
    external:
      name: kin-network

