from kin_reports_generation.domain.services.predicting.preprocessing.interface import ITextPreprocessor
from kin_reports_generation.domain.services.predicting.preprocessing.preprocessor import TextPreprocessor
from kin_reports_generation.domain.services.predicting.predictor.interface import IPredictor
