from kin_reports_generation.domain.services.predicting.preprocessing.interface import IPredictor, ITextPreprocessor
from kin_reports_generation.domain.services.predicting.preprocessing.preprocessor import TextPreprocessor
