"""empty message

Revision ID: 0f5f72d423aa
Revises: 11d8b5d89f6f
Create Date: 2023-07-10 14:20:51.314812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f5f72d423aa'
down_revision = '11d8b5d89f6f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
