"""empty message

Revision ID: 11d8b5d89f6f
Revises: 881cff2ca394
Create Date: 2023-07-04 12:13:47.793321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11d8b5d89f6f'
down_revision = '881cff2ca394'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
