"""empty message

Revision ID: 13729f4c604a
Revises: b16c74b77dda
Create Date: 2023-08-30 06:58:58.046015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13729f4c604a'
down_revision = 'b16c74b77dda'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
