"""empty message

Revision ID: 1c2b03ba9f22
Revises: 987b4558a730
Create Date: 2023-12-14 05:57:37.453183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c2b03ba9f22'
down_revision = '987b4558a730'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
