"""empty message

Revision ID: 258497e0c698
Revises: 47582f50d428
Create Date: 2023-08-09 04:58:59.128427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '258497e0c698'
down_revision = '47582f50d428'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
