"""empty message

Revision ID: 277d5e7e45ef
Revises: f5c6a97f98d6
Create Date: 2023-09-27 09:49:10.804578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '277d5e7e45ef'
down_revision = 'f5c6a97f98d6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
