"""empty message

Revision ID: 2c24c659617c
Revises: 3d51fe7ebae6
Create Date: 2023-12-21 06:04:13.103967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c24c659617c'
down_revision = '3d51fe7ebae6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
