"""empty message

Revision ID: 31adf680b2a3
Revises: 9631e3828059
Create Date: 2023-08-29 14:03:29.017772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31adf680b2a3'
down_revision = '9631e3828059'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
