"""empty message

Revision ID: 35c90254854a
Revises: e9e84812d40b
Create Date: 2023-11-27 05:52:36.659117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35c90254854a'
down_revision = 'e9e84812d40b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
