"""empty message

Revision ID: 362ddf66a34a
Revises: 258497e0c698
Create Date: 2023-08-11 09:58:08.744681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '362ddf66a34a'
down_revision = '258497e0c698'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
