"""empty message

Revision ID: 3d51fe7ebae6
Revises: e8fa05cb7dcd
Create Date: 2023-12-15 07:48:35.518392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d51fe7ebae6'
down_revision = 'e8fa05cb7dcd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
