"""empty message

Revision ID: 400347878486
Revises: 9b0c8d6d6916
Create Date: 2023-10-27 10:20:55.920027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '400347878486'
down_revision = '9b0c8d6d6916'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
