"""empty message

Revision ID: 47582f50d428
Revises: fe54a7b89c1a
Create Date: 2023-08-08 12:48:02.820133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47582f50d428'
down_revision = 'fe54a7b89c1a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
