"""empty message

Revision ID: 4d2c1ab67927
Revises: 56079340e4df
Create Date: 2023-06-25 07:49:23.391038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d2c1ab67927'
down_revision = '56079340e4df'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
