"""empty message

Revision ID: 56079340e4df
Revises: 85b889d4569a
Create Date: 2023-06-22 05:33:50.616604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56079340e4df'
down_revision = '85b889d4569a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
