"""empty message

Revision ID: 56a34ba8476b
Revises: 4d2c1ab67927
Create Date: 2023-06-26 05:13:25.646011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56a34ba8476b'
down_revision = '4d2c1ab67927'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
