"""empty message

Revision ID: 6ca720aecc5a
Revises: 13729f4c604a
Create Date: 2023-09-03 07:11:57.963525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ca720aecc5a'
down_revision = '13729f4c604a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
