"""empty message

Revision ID: 7183391d33ed
Revises: d48a2146903e
Create Date: 2023-07-25 05:16:42.471374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7183391d33ed'
down_revision = 'd48a2146903e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
