"""empty message

Revision ID: 82801599a28e
Revises: 2c24c659617c
Create Date: 2023-12-21 06:27:26.292084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82801599a28e'
down_revision = '2c24c659617c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
