"""empty message

Revision ID: 881cff2ca394
Revises: 56a34ba8476b
Create Date: 2023-07-02 14:56:32.459512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '881cff2ca394'
down_revision = '56a34ba8476b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
