"""empty message

Revision ID: 9631e3828059
Revises: 362ddf66a34a
Create Date: 2023-08-28 06:40:54.661519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9631e3828059'
down_revision = '362ddf66a34a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
