"""empty message

Revision ID: 987b4558a730
Revises: de1a67a55967
Create Date: 2023-12-08 08:18:00.159463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '987b4558a730'
down_revision = 'de1a67a55967'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
