"""empty message

Revision ID: 9b0c8d6d6916
Revises: 277d5e7e45ef
Create Date: 2023-10-24 05:44:18.672501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b0c8d6d6916'
down_revision = '277d5e7e45ef'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
