"""empty message

Revision ID: a922426d6f01
Revises: fa4ff2ae0e9a
Create Date: 2023-08-01 04:51:32.988643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a922426d6f01'
down_revision = 'fa4ff2ae0e9a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
