"""empty message

Revision ID: b16c74b77dda
Revises: 31adf680b2a3
Create Date: 2023-08-29 16:46:49.773250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b16c74b77dda'
down_revision = '31adf680b2a3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
