"""empty message

Revision ID: b8ee2a59b78d
Revises: 82801599a28e
Create Date: 2023-12-22 06:49:47.801626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8ee2a59b78d'
down_revision = '82801599a28e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
