"""empty message

Revision ID: ba6b1e7b974d
Revises: b8ee2a59b78d
Create Date: 2024-01-07 07:33:06.120716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba6b1e7b974d'
down_revision = 'b8ee2a59b78d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
