"""empty message

Revision ID: d48a2146903e
Revises: f7a96c5fd8ad
Create Date: 2023-07-16 12:52:48.033216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd48a2146903e'
down_revision = 'f7a96c5fd8ad'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
