"""empty message

Revision ID: e4e3c83a845c
Revises: 66868d1f0674
Create Date: 2023-06-01 19:07:23.238152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4e3c83a845c'
down_revision = '66868d1f0674'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('is_fetching', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_foreign_key(None, 'channel_rating', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'user_channel', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_channel', type_='foreignkey')
    op.drop_constraint(None, 'channel_rating', type_='foreignkey')
    op.drop_table('user')
    # ### end Alembic commands ###
