"""empty message

Revision ID: e8fa05cb7dcd
Revises: 1c2b03ba9f22
Create Date: 2023-12-15 07:31:21.083866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8fa05cb7dcd'
down_revision = '1c2b03ba9f22'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
