"""empty message

Revision ID: f5c6a97f98d6
Revises: 6ca720aecc5a
Create Date: 2023-09-03 07:21:39.060883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5c6a97f98d6'
down_revision = '6ca720aecc5a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
