"""empty message

Revision ID: f7a96c5fd8ad
Revises: 0f5f72d423aa
Create Date: 2023-07-16 11:56:24.974859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7a96c5fd8ad'
down_revision = '0f5f72d423aa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
