"""empty message

Revision ID: fa4ff2ae0e9a
Revises: ff56ddd6473d
Create Date: 2023-07-31 05:12:51.983122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa4ff2ae0e9a'
down_revision = 'ff56ddd6473d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
