"""empty message

Revision ID: ff56ddd6473d
Revises: 7183391d33ed
Create Date: 2023-07-26 05:25:13.365609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff56ddd6473d'
down_revision = '7183391d33ed'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
