version: '3'

services:
  postgres:
    image: "postgres:9.6"
    container_name: "postgres"
    volumes:
      - pgdata:/var/lib/postgresql/data/
    ports:
      - "5431:5432"
    networks:
      - kin-network
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=kin-txt
      - POSTGRES_USER=kin-txt-user
      - POSTGRES_PASSWORD=kin-txt-password

  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: "rabbitmq"
    environment:
      - RABBITMQ_DEFAULT_USER=kin-txt-user
      - RABBITMQ_DEFAULT_PASS=kin-txt-password
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      - kin-network

networks:
  kin-network:
    name: kin-network
    external: true

volumes:
  pgdata:
  cache:
  mongodb_data_container:
