version: '3'

services:
  postgres:
    image: "postgres:9.6"
    container_name: "postgres"
    volumes:
      - pgdata:/var/lib/postgresql/data/
    networks:
      - kin-network
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=kin-txt
      - POSTGRES_USER=kin-txt-user
      - POSTGRES_PASSWORD=kin-txt-password

  redis:
    image: redis:6.2-alpine
    container_name: "redis"
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - cache:/data
    networks:
      - kin-network

  mongo:
    image: "mongo:6.0.3"
    container_name: "mongo"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=kin-txt-user
      - MONGO_INITDB_ROOT_PASSWORD=kin-txt-password
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_container:/data/db
    networks:
      - kin-network

  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: "rabbitmq"
    environment:
      - RABBITMQ_DEFAULT_USER=kin-txt-user
      - RABBITMQ_DEFAULT_PASS=kin-txt-password
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      - kin-network

networks:
  kin-network:
    name: kin-network
    external: true

volumes:
  pgdata:
  cache:
  mongodb_data_container:
