replicaCount: 1

image:
  repository: kinfi4/kin-frontend
  pullPolicy: Always
  tag: latest

imagePullSecrets: []

ingress:
  enabled: true
  annotations: {}
  className: ""
  host: "localhost"
  path: "/"
  pathType: Prefix
  tls: false  # Enable TLS if true
  tlsSecret: ""  # Name of the TLS secret (if TLS is enabled)


configmapName: kin-frontend-configmap

podSecurityContext: {}
securityContext: {}
resources: {}
podAnnotations: {}

service:
  type: ClusterIP
  port: 80


settings:
  LOG_LEVEL: INFO
  REACT_APP_STATISTICS_SERVICE_URL: "http://kin-api-gateway:80/api/statistics/v1"
  REACT_APP_MODEL_TYPES_URL: "http://kin-api-gateway:80/api/model-types/v1"
  REACT_APP_GENERIC_REPORTS_BUILDER_URL: "http://kin-api-gateway:80/api/generic-builder/v1"
