"""New migration

Revision ID: 885cadbdce4e
Revises: 
Create Date: 2024-03-23 11:31:42.565712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '885cadbdce4e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model',
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('model_type', sa.Enum('SKLEARN', 'KERAS', 'BUILTIN', name='modeltypes2'), nullable=False),
    sa.Column('category_mapping', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('model_status', sa.Enum('VALIDATED', 'VALIDATION_FAILED', 'VALIDATING', 'CREATED', name='modelstatuses2'), nullable=False),
    sa.Column('validation_message', sa.String(), nullable=True),
    sa.Column('original_model_file_name', sa.String(), nullable=True),
    sa.Column('original_tokenizer_file_name', sa.String(), nullable=True),
    sa.Column('owner_username', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['owner_username'], ['public.user.username'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('code'),
    schema='public'
    )
    op.create_table('visualization_template',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('content_types', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('visualization_diagram_types', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('owner_username', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['owner_username'], ['public.user.username'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_table('model_preprocessing_config',
    sa.Column('lowercase', sa.Boolean(), nullable=False),
    sa.Column('remove_links', sa.Boolean(), nullable=False),
    sa.Column('remove_emoji', sa.Boolean(), nullable=False),
    sa.Column('remove_punctuation', sa.Boolean(), nullable=False),
    sa.Column('remove_extra_spaces', sa.Boolean(), nullable=False),
    sa.Column('remove_html_tags', sa.Boolean(), nullable=False),
    sa.Column('remove_stop_words', sa.Boolean(), nullable=False),
    sa.Column('stop_words_file_original_name', sa.String(), nullable=True),
    sa.Column('lemmatize_text', sa.Boolean(), nullable=False),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('max_tokens', sa.Integer(), nullable=True),
    sa.Column('padding', sa.Enum('PRE', 'POST', name='possiblepaddingtruncating2'), nullable=False),
    sa.Column('truncating', sa.Enum('PRE', 'POST', name='possiblepaddingtruncating2'), nullable=False),
    sa.Column('model_code', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['model_code'], ['public.model.code'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('model_code'),
    schema='public'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('model_preprocessing_config', schema='public')
    op.drop_table('visualization_template', schema='public')
    op.drop_table('model', schema='public')
    # ### end Alembic commands ###
