build:
	docker compose build

run-silent:
	docker compose up -d

run:
	docker compose up

logs:
	docker compose logs -f 

format:
	docker compose run --rm --no-deps kin-frontend npx prettier --write .
