version: '3'

services:
  model-types-api:
    build:
      context: .
      dockerfile: etc/service/Dockerfile
    image: 'kin-model-types'
    container_name: 'kin-model-types-api'
    command: bash -c "alembic upgrade head && python -m kin_model_types run-server"
    env_file:
      - etc/service/env/.dev.env
    ports:
      - "8004:8000"
    networks:
      - kin-network
    volumes:
      - ./etc/service/migrations:/app/migrations
      - ./etc/service/alembic.ini:/app/alembic.ini
      - ./src/kin_model_types:/app/kin_model_types
      - ./src/poetry.lock:/app/poetry.lock
      - ./src/pyproject.toml:/app/pyproject.toml
      - ./submodules:/submodules
      - /home/kinfi4/compiled-models/kin-news/:/models

  model-types-consumer:
    build:
      context: .
      dockerfile: etc/service/Dockerfile
    image: 'kin-model-types'
    container_name: 'kin-model-types-consumer'
    command: bash -c "python -m kin_model_types consume"
    env_file:
      - etc/service/env/.dev.env
    networks:
      - kin-network
    volumes:
      - ./etc/service/migrations:/app/migrations
      - ./etc/service/alembic.ini:/app/alembic.ini
      - ./src/kin_model_types:/app/kin_model_types
      - ./src/poetry.lock:/app/poetry.lock
      - ./src/pyproject.toml:/app/pyproject.toml
      - ./submodules:/submodules
      - /home/kinfi4/compiled-models/kin-news/:/models

networks:
  kin-network:
    name: kin-network
    external: true
