replicaCount: 1

image:
  repository: kin-frontend
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []


configmapName: kin-frontend-configmap

podSecurityContext: {}
securityContext: {}
resources: {}
podAnnotations: {}
podLabels: {}

service:
  type: ClusterIP
  port: 80


settings:
  LOG_LEVEL: INFO
  REACT_APP_STATISTICS_SERVICE_URL: "http://kin-api-gateway:80/api/statistics/v1"
  REACT_APP_MODEL_TYPES_URL: "http://kin-api-gateway:80/api/model-types/v1"
  REACT_APP_GENERIC_REPORTS_BUILDER_URL: "http://kin-api-gateway:80/api/generic-builder/v1"
