version: '3'

services:
  builtin-reports-builder-consumer:
    build:
      context: .
      dockerfile: etc/kin-reports-builder/Dockerfile
    image: 'kin-builtin-models-reports-builder'
    container_name: 'builtin-reports-builder-consumer'
    command: bash -c "python -m kin_builtin_models consume"
    env_file:
      - etc/kin-reports-builder/env/.dev.env
    networks:
      - kin-network
    volumes:
      - ./src/kin_builtin_models:/app/kin_builtin_models
      - ./src/poetry.lock:/app/poetry.lock
      - ./src/pyproject.toml:/app/pyproject.toml
      - ./submodules:/submodules
      - kin-reports-builder-models:/models

  builtin-reports-builder-celery-worker:
    build:
      context: .
      dockerfile: etc/kin-reports-builder/Dockerfile
    image: 'kin-builtin-models-reports-builder'
    container_name: 'builtin-reports-builder-celery-worker'
    command: bash -c "python -m kin_builtin_models run-tasks"
    env_file:
      - etc/kin-reports-builder/env/.dev.env
    networks:
      - kin-network
    volumes:
      - ./src/kin_builtin_models:/app/kin_builtin_models
      - ./src/poetry.lock:/app/poetry.lock
      - ./src/pyproject.toml:/app/pyproject.toml
      - ./submodules:/submodules
      - kin-reports-builder-models:/models
    depends_on:
      - builtin-reports-builder-consumer

networks:
  kin-network:
    external:
      name: kin-network

volumes:
    kin-reports-builder-models:
