secrets:
  common_secrets:
    secretName: common-secrets

replicaCount: 1

image:
  repository: kinfi4/kin-model-types
  pullPolicy: IfNotPresent
  tag: latest

imagePullSecrets: []


configmapName: kin-model-types-configmap

podSecurityContext: {}
securityContext: {}
resources: {}
podAnnotations: {}
podLabels: {}

service:
  type: ClusterIP
  port: 8000


settings:
  DEBUG: 1
  MODELS_STORAGE_PATH: /models
  LOG_LEVEL: INFO
  TOKEN_LIFE_MINUTES: 1200
  CELERY_BROKER_URL: ""
  CELERY_RESULT_BACKEND: ""
