secrets:
  common_secrets:
    secretName: common-secrets

replicaCount: 1

image:
  repository: kinfi4/kin-statistics
  pullPolicy: Always
  tag: latest

imagePullSecrets: []


configmapName: kin-statistics-configmap
pvcName: kin-statistics-pvc

podSecurityContext: {}
securityContext: {}
resources: {}
podAnnotations: {}
podLabels: {}

service:
  type: ClusterIP
  port: 8000


settings:
  DEBUG: 1
  LOG_LEVEL: INFO
  TOKEN_LIFE_MINUTES: 1200
  USER_REPORTS_FOLDER_PATH: /app/kin_statistics_api/data/reports/

  CELERY_BROKER_URL: ""
  CELERY_RESULT_BACKEND: ""
