apiVersion: v1
kind: Service
metadata:
  name: "kin-model-types-service"
  labels:
    {{- include "kin-model-types.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "kin-model-types.selectorLabels" . | nindent 4 }}
