version: '3'

services:
  generic-builder-consumer:
    build:
      context: .
      dockerfile: etc/service/Dockerfile
    image: 'kin-generic-reports-builder'
    container_name: 'kin-generic-builder-consumer'
    command: bash -c "python -m kin_generic_builder consume"
    env_file:
      - etc/service/env/.dev.env
    networks:
      - kin-network
    volumes:
      - ./src/kin_generic_builder:/app/kin_generic_builder
      - ./src/poetry.lock:/app/poetry.lock
      - ./src/pyproject.toml:/app/pyproject.toml
      - ./submodules:/submodules
      - kin-reports-generic-models:/models

  generic-builder-api:
    build:
      context: .
      dockerfile: etc/service/Dockerfile
    image: 'kin-generic-reports-builder'
    container_name: 'kin-generic-builder-api'
    command: bash -c "python -m kin_generic_builder run-server"
    env_file:
      - etc/service/env/.dev.env
    networks:
      - kin-network
    volumes:
      - ./src/kin_generic_builder:/app/kin_generic_builder
      - ./src/poetry.lock:/app/poetry.lock
      - ./src/pyproject.toml:/app/pyproject.toml
      - ./submodules:/submodules
      - kin-reports-generic-models:/models


networks:
  kin-network:
    name: kin-network
    external: true

volumes:
    kin-reports-generic-models: