apiVersion: v1
kind: ConfigMap
metadata:
    name: {{ .Values.configmapName }}
data:
    DEBUG: '{{ .Values.settings.DEBUG }}'
    MODELS_STORAGE_PATH: '{{ .Values.settings.MODELS_STORAGE_PATH }}'
    LOG_LEVEL: '{{ .Values.settings.LOG_LEVEL }}'
    TOKEN_LIFE_MINUTES: '{{ .Values.settings.TOKEN_LIFE_MINUTES }}'

    CELERY_BROKER_URL: '{{ .Values.settings.CELERY_BROKER_URL }}'
    CELERY_RESULT_BACKEND: '{{ .Values.settings.CELERY_RESULT_BACKEND }}'
