apiVersion: apps/v1
kind: Deployment
metadata:
  name: "kin-model-types-api"
  labels:
    {{- include "kin-model-types.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "kin-model-types.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "kin-model-types.labels" . | nindent 8 }}
	    {{- with .Values.podLabels }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}-api
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          command: [ "python", "-m", "kin_model_types", "run-server" ]
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          envFrom:
            - configMapRef:
                name: {{ .Values.configmapName }}
                optional: false
          env:
          - name: RABBITMQ_CONNECTION_STRING
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secrets.common_secrets.secretName }}
                key: message-broker-connection-string
          - name: MONGO_DB_CONNECTION_STRING
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secrets.common_secrets.secretName }}
                key: mongo-db-connection-string
          - name: SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secrets.common_secrets.secretName }}
                key: secret-key
          - name: KIN_TOKEN
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secrets.common_secrets.secretName }}
                key: kin-token
          - name: ALLOWED_HOSTS
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secrets.common_secrets.secretName }}
                key: allowed-hosts
