apiVersion: v1
kind: ConfigMap
metadata:
    name: {{ .Values.configmapName }}
data:
    LOG_LEVEL: '{{ .Values.settings.LOG_LEVEL }}'
    TOKEN_LIFE_MINUTES: '{{ .Values.settings.TOKEN_LIFE_MINUTES }}'
    DEBUG: '{{ .Values.settings.DEBUG }}'
    USER_REPORTS_FOLDER_PATH: '{{ .Values.settings.USER_REPORTS_FOLDER_PATH }}'

    CELERY_BROKER_URL: '{{ .Values.settings.CELERY_BROKER_URL }}'
    CELERY_RESULT_BACKEND: '{{ .Values.settings.CELERY_RESULT_BACKEND }}'
