version: '3'

services:
  nginx:
    build:
      context: .
      dockerfile: ./etc/service/Dockerfile
    container_name: kin-api-gateway
    env_file:
      - ./etc/service/env/.dev.env
    restart: 'no'
    networks:
      - kin-network
    ports:
      - "8080:80"

networks:
  kin-network:
    external:
      name: kin-network
