UUID = 1000

build:
	docker compose build

run-silent:
	docker compose up -d

run:
	docker compose up

logs:
	docker compose logs -f 

stop:
	docker compose stop

restart:
	docker compose stop
	docker compose up -d
