secrets:
  message_broker_url:
    secretName: message_broker_url
  mongo_url:
    secretName: mongo_url
  common_secrets:
    secretName: common_secrets
  celery:
    secretName: celery

replicaCount: 1

image:
  repository: kin-model-types
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []


configmapName: kin-model-types-configmap

podSecurityContext: {}
securityContext: {}
resources: {}
podAnnotations: {}
podLabels: {}

service:
  type: ClusterIP
  port: 8000


settings:
  MODELS_STORAGE_PATH: /models
  LOG_LEVEL: INFO
  TOKEN_LIFE_MINUTES: 1200
