# Generated by Django 3.2 on 2022-10-11 10:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=255, verbose_name='display_name')),
                ('link', models.CharField(max_length=255, verbose_name='link')),
                ('subscribers', models.ManyToManyField(related_query_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
