# Generated by Django 4.1.2 on 2022-10-16 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='display_name',
        ),
    ]
