secrets:
  common_secrets:
    secretName: common-secrets
  telegram:
    secretName: telegram
  redit:
    secretName: redit

replicaCount: 1

image:
  repository: kinfi4/kin-generic-reports-builder
  pullPolicy: IfNotPresent
  tag: latest

imagePullSecrets: []


configmapName: kin-generic-models-configmap
pvcName: kin-generic-models-pvc

podSecurityContext: {}
securityContext: {}
resources: {}
podAnnotations: {}
podLabels: {}

service:
  type: ClusterIP
  port: 8000


settings:
  DEBUG: 1
  MODELS_STORAGE_PATH: /models
  LOG_LEVEL: INFO
  RABBITMQ_QUEUE_NAME: builtin_models_queue
  STATISTICS_SERVICE_URL: http://kin-statistics:8000/api/statistics/v1
  MODEL_TYPES_SERVICE_URL: http://kin-model-types:8000/api/model-types/v1

  TF_CPP_MIN_LOG_LEVEL: 2
  CELERY_REDIRECT_STDOUTS_LEVEL: INFO

  STOP_WORDS_STORAGE_PATH: /app/kin_generic_builder/data/stop-words

  CELERY_BROKER_URL: redis://:ivDD1GD0Tu@redis-master:6379/5
  CELERY_RESULT_BACKEND: redis://:ivDD1GD0Tu@redis-master:6379/5
