"""empty message

Revision ID: 65f0f302518a
Revises: 
Create Date: 2023-01-21 09:26:01.347735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65f0f302518a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_generate_reports',
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('reports_generated_count', sa.Integer(), nullable=True)
    )
    op.create_table('user_report',
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('report_id', sa.Integer(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_report')
    op.drop_table('user_generate_reports')
    # ### end Alembic commands ###
