"""New migration

Revision ID: f44846e7340c
Revises: 
Create Date: 2024-01-08 17:37:58.546098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f44846e7340c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_generate_reports',
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('reports_generated_count', sa.Integer(), nullable=True)
    )
    op.create_table('user_report',
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('report_id', sa.Integer(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_report')
    op.drop_table('user_generate_reports')
    # ### end Alembic commands ###
