apiVersion: v1
kind: ConfigMap
metadata:
    name: {{ .Values.configmapName }}
data:
    DEBUG: '{{ .Values.settings.DEBUG }}'
    MODEL_STORAGE_PATH: '{{ .Values.settings.MODEL_STORAGE_PATH }}'
    STOP_WORDS_STORAGE_PATH: '{{ .Values.settings.STOP_WORDS_STORAGE_PATH }}'

    LOG_LEVEL: '{{ .Values.settings.LOG_LEVEL }}'

    CELERY_REDIRECT_STDOUTS_LEVEL: '{{ .Values.settings.CELERY_REDIRECT_STDOUTS_LEVEL }}'
    TF_CPP_MIN_LOG_LEVEL: '{{ .Values.settings.TF_CPP_MIN_LOG_LEVEL }}'

    STATISTICS_SERVICE_URL: '{{ .Values.settings.STATISTICS_SERVICE_URL }}'
    MODEL_TYPES_SERVICE_URL: '{{ .Values.settings.MODEL_TYPES_SERVICE_URL }}'

    CELERY_BROKER_URL: '{{ .Values.settings.CELERY_BROKER_URL }}'
    CELERY_RESULT_BACKEND: '{{ .Values.settings.CELERY_RESULT_BACKEND }}'
