apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pvcName }}
spec:
  storageClassName: local-disk
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
