apiVersion: v1
kind: Service
metadata:
  name: "kin-generic-models-service"
  labels:
    {{- include "kin-generic-models.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "kin-generic-models.selectorLabels" . | nindent 4 }}
