name: Kin-TXT CI Workflow

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  ci-kin-model-types:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.modified, 'kin-model-types/') || contains(github.event.head_commit.added, 'kin-model-types/')
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Build and Test kin-model-types
        run: |
          cd kin-model-types
          docker build -f etc/service/Dockerfile -t kin-model-types .
          docker run --rm kin-model-types /bin/sh -c "mypy kin_model_types"
  ci-kin-statistics:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.modified, 'kin-statistics/') || contains(github.event.head_commit.added, 'kin-statistics/')
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Build and Test kin-statistics
        run: |
          cd kin-statistics
          docker build -f etc/service/Dockerfile -t kin-statistics .
          docker run --rm kin-statistics /bin/sh -c "mypy kin_statistics_api"
     
